<?php

declare(strict_types=1);

return [

    /*
    |--------------------------------------------------------------------------
    | Root namespace for generated domain code
    |--------------------------------------------------------------------------
    |
    | Every domain module generated by ddd:* commands is namespaced beneath
    | this root, e.g. "{base_namespace}\\Contact\\Domain\\Entities".
    |
    */

    'base_namespace' => 'App\\Domains',

    /*
    |--------------------------------------------------------------------------
    | Root path for generated domain code
    |--------------------------------------------------------------------------
    |
    | Must correspond to base_namespace under your composer.json autoload map.
    |
    */

    'base_path' => app_path('Domains'),

    /*
    |--------------------------------------------------------------------------
    | Stub overrides
    |--------------------------------------------------------------------------
    |
    | Set to a path (e.g. base_path('stubs/ddd')) after running
    | `vendor:publish --tag=ddd-stubs` to customize generated file templates.
    | Null falls back to the package's own stubs.
    |
    */

    'stubs_path' => null,

    /*
    |--------------------------------------------------------------------------
    | Auto-register domain service providers
    |--------------------------------------------------------------------------
    |
    | When true, ddd:domain appends the new {Domain}ServiceProvider::class
    | into bootstrap/providers.php automatically.
    |
    */

    'auto_register_providers' => true,

    /*
    |--------------------------------------------------------------------------
    | Providers file override
    |--------------------------------------------------------------------------
    |
    | Path to the bootstrap/providers.php file that auto_register_providers
    | appends to. Null uses the application's default. Override only for
    | non-standard app structures or test isolation.
    |
    */

    'providers_file' => null,

];
